[DPE-5289]: CI uses new juju versions
canonical/mongos-k8s-operator pull request #29
Opened 2024-08-28 15:44 UTC by Gu1nness

## Issue

We need to keep our CI up to date.

## Solution

* Use juju 3.5.3 in regular runs
* Runs also 3.6/beta on nightly runs

2024-08-29 09:14 UTC, Mehdi-Bendriss requested changes

2024-08-29 09:14 UTC, Mehdi-Bendriss commented on pyproject.toml
>  pytest = "^8.1.1"
above this line, could you change the pylibjuju version to `3.5.0.0`?

2024-08-29 09:14 UTC, Mehdi-Bendriss commented on .github/workflows/ci.yaml
> +          - snap_channel: 3.6/beta
3.5/stable ?

2024-08-30 09:31 UTC, carlcsaposs-canonical approved these changes
you may need to specify base when deploying with libjuju so that it doesn't default to focal cc @shayancanonical

2024-08-30 13:32 UTC, Mehdi-Bendriss approved these changes

2024-09-02 06:46 UTC, MiaAltieri approved these changes
LGTM - don't worry about the TLS tests, those are flakey and an issue has been filed

2024-09-02 07:43 UTC, merged